### PR TITLE
Electron arguments

### LINKED ISSUE #36: Source map not working for main process
When I create an app using `yarn create @electron-esbuild/app` using the `main-ts` or `react-vite-ts` templates, and I make `main.ts` throw an exception (e.g., add a `throw Error('test')` at the bottom), the stack trace does not use a source map:

```log
[...]
App threw an error during load
Error: main
    at Object.<anonymous> (.../myapp/dist/main/main.js:489:7)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at loadApplicationPackage (.../myapp/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:110:16)
    at Object.<anonymous> (.../exp/myapp/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:222:9)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
```

But I can see that the source map is generated:

```console
% ls -al dist/main 
total 88
drwxr-xr-x  6 user  staff    192 Jan  8 11:35 .
drwxr-xr-x  3 user  staff     96 Jan  8 11:31 ..
-rw-r--r--  1 user  staff  16311 Jan  8 11:36 main.js
-rw-r--r--  1 user  staff  20472 Jan  8 11:36 main.js.map
-rw-r--r--  1 user  staff     93 Jan  8 11:36 preload.js
-rw-r--r--  1 user  staff    170 Jan  8 11:36 preload.js.map
```

Adding `sourcemap: true` to `tsconfig.json` and `esbuild.main.config.ts` did not help.

[Node 12 added a `--enable-source-maps`](https://nodejs.org/dist/latest-v16.x/docs/api/cli.html#--enable-source-maps) - and this may become the default nodejs/node#38817

Not sure how to enable that for the node in Electron?

### LINKED ISSUE #38: Feature request: Allow command line arguments to be passed through to app when using `dev`
Electron apps sometimes needs to accept command line arguments, and while this works as normal if the app is packaged, it doesn't work if it is spawned using `electron-esbuild dev` - currently any arguments passed is swallowed and not passed on to the main process.

I think the relevant lines are https://github.com/Kiyozz/electron-esbuild/blob/34f142a47dd4e3fd4a6cf3f7c6760b0e6be98d20/packages/electron-esbuild/src/commands/dev.mts#L44

It may be useful to see how [electron-webpack's dev server gets around this](https://github.com/electron-userland/electron-webpack/blob/41057bb1c1341cacc2df8180225c28c2cabfc3d3/packages/electron-webpack/src/dev/dev-runner.ts#L65) - I guess by using the `ELECTRON_ARGS` env variable to avoid "polluting" the command line args any more than necessary.

### PR DESCRIPTION
**Pull request by Kiyozz**
Closes #36
Closes #38

### CODE REVIEW

**Comment by beorn** [comment]
That's great!

To support #38 as well, it's not ideal to have any regular electorn-esbuild arguments appear on the command line, in the `process.argv`, as it means every app would have to deal with the electron-esbuild arguments as well as its own; essentially their CLI API surface would be electron-esbuild's options plus their own  - but only when run as `dev`.  Ideally the situation should be the same whether the app is run as dev or as the prepackaged app.

I think a nice solution is to have the dev server pass all electron-esbuild arguments to electron using the ELECTRON_OPTIONS env variable, so that the command line to the app is just whatever you passed to it after dev.

Packages such as [commanderjs](https://github.com/tj/commander.js/) has support for being run inside of electron apps - [handling the case of whether they are prepackaged or run as you do in the devserver](https://github.com/tj/commander.js/#bits-and-pieces).

**Comment by Kiyozz** [comment]
Actually, this pr fix #38 too. All inputs after `--` is passed through electron in dev.

I don't understand the problem here. I have an electron app my self and use argv too without any problem using electron-esbuild (no commanderjs or whatever).

Your app will not have any electron-esbuild options has being called via `electron yourjs.js your_args`.

This is not the electron-esbuild's job to handle argv if running prepackaged or dev mode.

**Comment by beorn** [comment]
Ah ok my mistake then!  I thought `process.argv` in main.ts would by default end up including the `--inspect` etc flags, which the app would then have to understand and remove -- instead of just the minimal electron and main.js argv, which although is different from when the app is packaged, is easy enough to have one special case for (and which commanderjs at least has special support for).

**Comment by beorn** [comment]
Ok, my explanation wasn't very good.  Sorry about that.

To illustrate the problem, given a `main.ts` with this snippet:
```typescript
import { Command } from 'commander'
console.log('argv', process.argv)
const program = new Command()
program
  .argument('[path]', 'Folder to sync', '/tmp/')
  .parse()
```

When run as `electron-esbuild dev` (no additional arguments passed) it will output this:
```console
argv [
  '.../electron-esbuild/node_modules/.pnpm/electron@16.0.7/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron',
  'dist/main/main.js',
  '--inspect=9223',
  '--remote-debugging-port=9222'
]
error: unknown option '--inspect=9223'
```

But if you pass the Electron arguments to Electron using the `ELECTRON_OPTIONS` env variable instead, the scripts won't see any of them and can just worry about its own command line arguments and options, similarly to the way the app currently works when it is packaged up.

**Comment by Kiyozz** [comment]
The problem here is: if the options are not passed in the command line, then the debugger/remote debugger will not start. Where did you find the ELECTRON_OPTIONS env? Is it from electron or just something from commanderjs ?

**Comment by beorn** [comment]
You are right, I was thinking of `ELECTRON_ARGS` which is a [feature of electron-webpack](https://github.com/electron-userland/electron-webpack/blob/41057bb1c1341cacc2df8180225c28c2cabfc3d3/packages/electron-webpack/src/dev/dev-runner.ts#L65) ([docs](https://webpack.electron.build/environment-variables#electron_args)), but which still appends the args to the command line.  I don't know if it is possible to affect electron without passing options as command line arguments?  Maybe by targeting the node and chromium process directly through their env variables, e.g.,

```javascript
NODE_OPTIONS = '--inspect=9223'
CHROMIUM_FLAGS = '--remote-debugging-port=9222'
```

though not sure if the CHROMIUM_FLAGS one really works, and if electron will not filter out one or both of them.

**Comment by Kiyozz** [comment]
I will look into it. If both env works, I will then use env variables instead.

**Comment by Kiyozz** [comment]
The next version will no longer inject `--inspect` and `--remote-debugging-port` by default.

You will need to use an IDE to start electron-esbuild in debug or use `electron-esbuild dev -- --inspect` to start the debugger and attach to it later. 

So, by default, no args will be injected to the electron process and libraries like commanderjs will no longer complains.

There is no way to start the remote-debugging unless you use a command line argument (`electron-esbuild dev -- --remote-debugging-port`).

To start the main process inspector, you need at least start `electron-esbuild` in an IDE, or by adding `--inspect` and attach to the inspector.

**Comment by beorn** [comment]
That makes sense, thanks!

**Comment by Kiyozz** [comment]
Available in 5.0.0

**Comment by beorn** [comment]
Thanks for the feature/upgrade!! 😁

**Pull request merged**
