### PR TITLE
Replace chokidar with esbuild.watch

### PR DESCRIPTION
**Pull request by Zertz**

### CODE REVIEW

**Comment by Kiyozz** [comment]
Why another pr ?

Huge changes are coming soon, that use monorepo with pnpm.

**Comment by Zertz** [comment]
Rebasing was a pain so I cherry-picked changes. Still blocked by PostCSS though so I'll leave it there for now and get back to it eventually.

**Comment by Kiyozz** [comment]
You could use the other branch instead of a new 😉.

If postcss plugin is not updating, we could create our own plugin (or you could 😁).

**Comment by Kiyozz** [comment]
Monorepo is live :)

**Pull request closed without merging**
